
import type { Metadata } from 'next';
import Input from '@/components/ui/input/input';
import Steps from '@/components/ui/steps/steps';

export const metadata: Metadata = {
  title: 'GScore | Authorization ',
  description: 'Generated by create next app',
}

export default function AuthorizationLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className='container'>
      <Steps />
      {children}
      <Input placeholder="Password" />
    </div>
  )
}
