import "./settings.sass";

import Title from "@/components/ui/title/title"

import { Metadata } from "next"
import Link from "next/link"
import PrivateRoute from "@/components/HOC/private-route";

export const metadata: Metadata = {
  title: 'GScore',
  description: 'Generated by create next app',
}

export default function SettingLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <PrivateRoute destinationPath="/settings">
      <div className="settings-layout">
        <div className="container">
          <Title titleText="Settings" />

          <div className="settings-layout__tabs">
            <Link href={"/settings"} className="settings-layout__link settings-layout_active">Personal info</Link>
            <Link href={"/settings/change-password"} className="settings-layout__link">Change password</Link>
          </div>

          {children}
        </div>
      </div>
    </PrivateRoute>
  )
}
